name: Config Update

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      run: |
        # 使用 GITHUB_TOKEN 进行认证，克隆当前仓库代码到工作目录
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
    
    - name: Setup Python environment
      run: |
        # 检查 Python 版本，如有必要，可使用 apt-get 安装指定版本
        python3 --version
        python3 -m pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        pip install pandas requests pyyaml

    - name: Setup sing-box
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.8.1/sing-box_1.8.1_linux_amd64.deb"
      run: |
        set -Eeuo pipefail
        wget -O sing-box.deb $SING_BOX_DEB_URL
        sudo dpkg -i sing-box.deb

    - name: Run script
      run: python ../convert.py
      working-directory: ./data/

    - name: Archive files
      run: tar -cvf ./data/rules_archive.tar --exclude="*.tar" -C ./data/ .

    - name: Move files to rule_json and rule_srs
      run: |
        mkdir -p ./rule_json/
        mkdir -p ./rule_srs/
        tar --wildcards -xvf ./data/rules_archive.tar -C ./rule_json/ '*.json'
        tar --wildcards -xvf ./data/rules_archive.tar -C ./rule_srs/ '*.srs'

    - name: Commit and push config.json
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        # 始终添加文件，新生成的文件会覆盖同名的旧文件
        git add ./data/rules_archive.tar
        git add ./rule_json/*.json
        git add ./rule_srs/*.srs
        git commit --allow-empty -m "Update rules"
        git push
